backend:
   name: git-gateway
   branch: master

media_folder: uploads

collections:
   -  label: Texte
      name: texts
      folder: 'data/texts'
      delete: false
      fields:
         -  name: title
         -  name: body
            widget: markdown
   -  label: Termine
      label_singular: Termin
      name: meetings
      
      folder: 'data/meetings'
      create: true
      fields:
         -  name: date
            widget: date
         -  name: title
         -  name: location         
      
   

