backend:
   name: git-gateway
   branch: master

media_folder: static/uploads

collections:

   -  name: texts
      label: Texte
      folder: 'data/texts'
      delete: false
      fields:
         -  name: title
         -  name: body
            widget: markdown

   -  name: meetings
      label: Termine
      label_singular: Termin
      folder: 'data/meetings'
      create: true
      fields:
         -  name: date
            widget: date
            label: Datum
            picker_utc: true
         -  name: time
            label: Zeit
            required: false
         -  name: title
            label: Titel
         -  name: location
            label: Location  
            required: false  
   
   -  name: locations
      label: Orte
      label_singular: Ort
      folder: 'data/locations' 
      create: true
      extension: 'yml'
      fields:
         -  name: name
            label: Name
         -  name: address_line_1
            label: Adress-Linie 1
            required: false
         -  name: address_line_2
            label: Adress-Linie 2
            required: false

   -  name: team
      label: Team
      label_singular: Team Member
      folder: 'data/team' 
      create: true
      extension: 'yml'
      fields:
         -  name: name
            label: Name
         -  name: description
            label: Beschreibung
            required: false
         -  name: company
            label: Firma
            required: false
         -  name: link
            label: Link
            required: false

   -  name: download
      label: Download
      folder: 'data/download'
      create: true
      extension: 'yml'
      fields: 
         -  name: title
            label: Titel
         -  name: file
            label: Datei
            widget: file


         
      
      
   

