backend:
   name: git-gateway
   branch: master

media_folder: uploads

collections:

   -  name: texts
      label: Texte
      folder: 'data/texts'
      delete: false
      fields:
         -  name: title
         -  name: body
            widget: markdown

   -  name: meetings
      label: Termine
      label_singular: Termin
      folder: 'data/meetings'
      create: true
      fields:
         -  name: date
            widget: date
            label: Datum
            picker_utc: true
         -  name: title
            label: Titel
         -  name: location
            label: Location    
   
   -  name: team
      label: Team
      label_singular: Team Member
      folder: 'data/team' 
      create: true
      extension: 'yml'
      fields:
         -  name: name
         -  name: description
         -  name: company
         -  name: link
         
      
      
   

